use crate::stream::PeekableStream;
use crate::token::Token;

pub struct Parser {
    pos: usize,

    /// Tokens generated by the lexer
    tokens: Vec<Tokens>
}

impl PeekableStream<Token> for Parser {
    fn pos(&mut self) -> &mut usize {
        &mut self.pos
    }

    fn is_eos(&self) -> bool {
        self.pos >= self.tokens.len()
    }

    fn peek(&self) -> Token {
        //if 
        self.tokens.get(self.pos).unwrap()
    }
}